### ISSUE TITLE
Uniqueness 

### ISSUE THREAD

**Issue by Yfeng-44** [SJTU-ACA-Lab/blue-porcelain#1]
Hi,

Thanks for your great contribution on GPGPU arch community. I'm wondering what is the key difference and unique feature of blue-porcelain over gpgpu-sim and/or AccelSim? 

regards

**Comment by chqqhc** [comment]
Thanks for raising the issue!

Our design provides a simulation of machine ISA through execution-driven simulation. Accel-Sim simulates machine ISA through trace-driven simulation.  Execution-driven simulation is only supported for virtual ISA on both of Accel-sim and  GPGPU-Sim.

**Comment by Yfeng-44** [comment]
Thanks for replying!

**Comment by Yfeng-44** [comment]
So in this case, is the target ISA here SASS?
